name: curiousbydesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfbfbf'
    - '#a8a8a8'
    - '#737373'
    - '#4f4f4f'
    - '#191919'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
